# Generated by Django 6.0.3 on 2026-06-25 01:15

from django.db import migrations


def seed_data(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    CommonExpense = apps.get_model('expenses', 'CommonExpense')
    
    # 1. Create global categories (user=None)
    categories = {
        'Хүнс': {'description': 'Хүнсний бүтээгдэхүүн, идэх уух зүйлс', 'color': '#4e79a7'},
        'Тээвэр': {'description': 'Автобус, такси, бензин, замын зардал', 'color': '#f28e2b'},
        'Гэр ахуй': {'description': 'Тог, дулаан, интернэт, байрны мөнгө', 'color': '#76b7b2'},
        'Эрүүл мэнд': {'description': 'Эм тариа, үзлэг, эрүүл мэндийн зардал', 'color': '#e15759'},
        'Чөлөөт цаг': {'description': 'Кофе, ресторан, кино, фитнес', 'color': '#59a14f'},
        'Бусад': {'description': 'Бусад өдөр тутмын зарлагууд', 'color': '#b07aa1'},
    }
    
    cat_objs = {}
    for name, data in categories.items():
        cat, created = Category.objects.get_or_create(
            name=name,
            user=None,  # Global category
            defaults={
                'description': data['description'],
                'color': data['color'],
                'is_income': False
            }
        )
        cat_objs[name] = cat

    # 2. Seed Common Expenses
    common_expenses_data = [
        # Food (Хүнс)
        {'name': 'Талх', 'category_name': 'Хүнс'},
        {'name': 'Сүү', 'category_name': 'Хүнс'},
        {'name': 'Өндөг', 'category_name': 'Хүнс'},
        {'name': 'Үхрийн мах (1кг)', 'category_name': 'Хүнс'},
        {'name': 'Цагаан будаа', 'category_name': 'Хүнс'},
        {'name': 'Хүнсний ногоо', 'category_name': 'Хүнс'},
        {'name': 'Жимс жимсгэнэ', 'category_name': 'Хүнс'},
        {'name': 'Цэвэр ус (1.5л)', 'category_name': 'Хүнс'},
        {'name': 'Шүүс / Ундаа', 'category_name': 'Хүнс'},
        
        # Transport (Тээвэр)
        {'name': 'Автобусны карт цэнэглэх', 'category_name': 'Тээвэр'},
        {'name': 'Такси / Ulaanbaatar Cab', 'category_name': 'Тээвэр'},
        {'name': 'Бензин АИ-92', 'category_name': 'Тээвэр'},
        {'name': 'Авто зогсоолын төлбөр', 'category_name': 'Тээвэр'},
        {'name': 'Авто угаалга', 'category_name': 'Тээвэр'},
        
        # Utilities (Гэр ахуй)
        {'name': 'Тогны мөнгө', 'category_name': 'Гэр ахуй'},
        {'name': 'Интернэтийн төлбөр', 'category_name': 'Гэр ахуй'},
        {'name': 'СӨХ / Байрны мөнгө', 'category_name': 'Гэр ахуй'},
        {'name': 'Кабелийн суваг', 'category_name': 'Гэр ахуй'},
        
        # Healthcare (Эрүүл мэнд)
        {'name': 'Эмийн сан / Эм', 'category_name': 'Эрүүл мэнд'},
        {'name': 'Эмчийн үзлэг / Шинжилгээ', 'category_name': 'Эрүүл мэнд'},
        
        # Leisure (Чөлөөт цаг)
        {'name': 'Кофе / Латте', 'category_name': 'Чөлөөт цаг'},
        {'name': 'Зоогийн газар / Үдийн хоол', 'category_name': 'Чөлөөт цаг'},
        {'name': 'Киноны тасалбар', 'category_name': 'Чөлөөт цаг'},
        {'name': 'Фитнес сарын гишүүнчлэл', 'category_name': 'Чөлөөт цаг'},
        {'name': 'Үсчин / Гоо сайхан', 'category_name': 'Чөлөөт цаг'},
    ]

    for item in common_expenses_data:
        cat = cat_objs.get(item['category_name'])
        CommonExpense.objects.get_or_create(
            name=item['name'],
            defaults={
                'category': cat,
                'description': f"Өдөр тутмын {item['name'].lower()}"
            }
        )


def reverse_seed_data(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    CommonExpense = apps.get_model('expenses', 'CommonExpense')
    
    CommonExpense.objects.all().delete()
    Category.objects.filter(user=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_commonexpense'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]

