# Generated by Django 6.0.3 on 2026-06-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_seed_common_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='next_recurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_interval',
            field=models.CharField(blank=True, choices=[('', 'Давтамжгүй'), ('daily', 'Өдөр бүр'), ('weekly', '7 хоног бүр'), ('monthly', 'Сар бүр')], default='', max_length=10),
        ),
    ]
